name: build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      
      - name: setup node.js environment
        uses: actions/setup-node@v2.1.0
      
      - name: npm install
        run: npm install
      
      - name: npm run build
        run: npm run build
